export const LOGIN = "LOGIN";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_MY_PRODUCTS = "FETCH_MY_PRODUCTS";
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const FETCH_PRODUCT_COMMENTS = "FETCH_PRODUCT_COMMENTS";
export const ADD_FLASH = "SET_FLASH";
export const REMOVE_FLASH = "REMOVE_FLASH"